#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlanjeFakture.LinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AppBaza")]
	public partial class AppBazaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArtikal(Artikal instance);
    partial void UpdateArtikal(Artikal instance);
    partial void DeleteArtikal(Artikal instance);
    partial void InsertProdavnica(Prodavnica instance);
    partial void UpdateProdavnica(Prodavnica instance);
    partial void DeleteProdavnica(Prodavnica instance);
    partial void InsertDobavljac(Dobavljac instance);
    partial void UpdateDobavljac(Dobavljac instance);
    partial void DeleteDobavljac(Dobavljac instance);
    partial void InsertFaktura(Faktura instance);
    partial void UpdateFaktura(Faktura instance);
    partial void DeleteFaktura(Faktura instance);
    partial void InsertFakturaStavka(FakturaStavka instance);
    partial void UpdateFakturaStavka(FakturaStavka instance);
    partial void DeleteFakturaStavka(FakturaStavka instance);
    partial void InsertKalkulacija(Kalkulacija instance);
    partial void UpdateKalkulacija(Kalkulacija instance);
    partial void DeleteKalkulacija(Kalkulacija instance);
    partial void InsertKupac(Kupac instance);
    partial void UpdateKupac(Kupac instance);
    partial void DeleteKupac(Kupac instance);
    partial void InsertNivelacije(Nivelacije instance);
    partial void UpdateNivelacije(Nivelacije instance);
    partial void DeleteNivelacije(Nivelacije instance);
    partial void InsertProdavac(Prodavac instance);
    partial void UpdateProdavac(Prodavac instance);
    partial void DeleteProdavac(Prodavac instance);
    partial void InsertUnosUMagacin(UnosUMagacin instance);
    partial void UpdateUnosUMagacin(UnosUMagacin instance);
    partial void DeleteUnosUMagacin(UnosUMagacin instance);
    #endregion
		
		public AppBazaDataContext() : 
				base(global::SlanjeFakture.Properties.Settings.Default.AppBazaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AppBazaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppBazaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppBazaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppBazaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Artikal> Artikals
		{
			get
			{
				return this.GetTable<Artikal>();
			}
		}
		
		public System.Data.Linq.Table<Prodavnica> Prodavnicas
		{
			get
			{
				return this.GetTable<Prodavnica>();
			}
		}
		
		public System.Data.Linq.Table<Dobavljac> Dobavljacs
		{
			get
			{
				return this.GetTable<Dobavljac>();
			}
		}
		
		public System.Data.Linq.Table<Faktura> Fakturas
		{
			get
			{
				return this.GetTable<Faktura>();
			}
		}
		
		public System.Data.Linq.Table<FakturaStavka> FakturaStavkas
		{
			get
			{
				return this.GetTable<FakturaStavka>();
			}
		}
		
		public System.Data.Linq.Table<Kalkulacija> Kalkulacijas
		{
			get
			{
				return this.GetTable<Kalkulacija>();
			}
		}
		
		public System.Data.Linq.Table<Kupac> Kupacs
		{
			get
			{
				return this.GetTable<Kupac>();
			}
		}
		
		public System.Data.Linq.Table<Nivelacije> Nivelacijes
		{
			get
			{
				return this.GetTable<Nivelacije>();
			}
		}
		
		public System.Data.Linq.Table<Prodavac> Prodavacs
		{
			get
			{
				return this.GetTable<Prodavac>();
			}
		}
		
		public System.Data.Linq.Table<UnosUMagacin> UnosUMagacins
		{
			get
			{
				return this.GetTable<UnosUMagacin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Artikal")]
	public partial class Artikal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SifraArtikla;
		
		private string _NazivArtikla;
		
		private System.Nullable<double> _NabavnaCenaINO;
		
		private System.Nullable<double> _NabavnaCenaRSD;
		
		private System.Nullable<int> _Rabat;
		
		private System.Nullable<double> _CenaPosleRabata;
		
		private System.Nullable<int> _Kolicina;
		
		private System.Nullable<double> _Marza;
		
		private System.Nullable<double> _RUC;
		
		private System.Nullable<double> _OsnovicaPoJM;
		
		private System.Nullable<int> _PDVStopa;
		
		private System.Nullable<double> _IznosPDVPoJM;
		
		private System.Nullable<double> _ProdajnaCena;
		
		private System.Nullable<int> _Otpad;
		
		private EntitySet<FakturaStavka> _FakturaStavkas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSifraArtiklaChanging(string value);
    partial void OnSifraArtiklaChanged();
    partial void OnNazivArtiklaChanging(string value);
    partial void OnNazivArtiklaChanged();
    partial void OnNabavnaCenaINOChanging(System.Nullable<double> value);
    partial void OnNabavnaCenaINOChanged();
    partial void OnNabavnaCenaRSDChanging(System.Nullable<double> value);
    partial void OnNabavnaCenaRSDChanged();
    partial void OnRabatChanging(System.Nullable<int> value);
    partial void OnRabatChanged();
    partial void OnCenaPosleRabataChanging(System.Nullable<double> value);
    partial void OnCenaPosleRabataChanged();
    partial void OnKolicinaChanging(System.Nullable<int> value);
    partial void OnKolicinaChanged();
    partial void OnMarzaChanging(System.Nullable<double> value);
    partial void OnMarzaChanged();
    partial void OnRUCChanging(System.Nullable<double> value);
    partial void OnRUCChanged();
    partial void OnOsnovicaPoJMChanging(System.Nullable<double> value);
    partial void OnOsnovicaPoJMChanged();
    partial void OnPDVStopaChanging(System.Nullable<int> value);
    partial void OnPDVStopaChanged();
    partial void OnIznosPDVPoJMChanging(System.Nullable<double> value);
    partial void OnIznosPDVPoJMChanged();
    partial void OnProdajnaCenaChanging(System.Nullable<double> value);
    partial void OnProdajnaCenaChanged();
    partial void OnOtpadChanging(System.Nullable<int> value);
    partial void OnOtpadChanged();
    #endregion
		
		public Artikal()
		{
			this._FakturaStavkas = new EntitySet<FakturaStavka>(new Action<FakturaStavka>(this.attach_FakturaStavkas), new Action<FakturaStavka>(this.detach_FakturaStavkas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraArtikla", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SifraArtikla
		{
			get
			{
				return this._SifraArtikla;
			}
			set
			{
				if ((this._SifraArtikla != value))
				{
					this.OnSifraArtiklaChanging(value);
					this.SendPropertyChanging();
					this._SifraArtikla = value;
					this.SendPropertyChanged("SifraArtikla");
					this.OnSifraArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivArtikla", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivArtikla
		{
			get
			{
				return this._NazivArtikla;
			}
			set
			{
				if ((this._NazivArtikla != value))
				{
					this.OnNazivArtiklaChanging(value);
					this.SendPropertyChanging();
					this._NazivArtikla = value;
					this.SendPropertyChanged("NazivArtikla");
					this.OnNazivArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NabavnaCenaINO", DbType="Float")]
		public System.Nullable<double> NabavnaCenaINO
		{
			get
			{
				return this._NabavnaCenaINO;
			}
			set
			{
				if ((this._NabavnaCenaINO != value))
				{
					this.OnNabavnaCenaINOChanging(value);
					this.SendPropertyChanging();
					this._NabavnaCenaINO = value;
					this.SendPropertyChanged("NabavnaCenaINO");
					this.OnNabavnaCenaINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NabavnaCenaRSD", DbType="Float")]
		public System.Nullable<double> NabavnaCenaRSD
		{
			get
			{
				return this._NabavnaCenaRSD;
			}
			set
			{
				if ((this._NabavnaCenaRSD != value))
				{
					this.OnNabavnaCenaRSDChanging(value);
					this.SendPropertyChanging();
					this._NabavnaCenaRSD = value;
					this.SendPropertyChanged("NabavnaCenaRSD");
					this.OnNabavnaCenaRSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rabat", DbType="Int")]
		public System.Nullable<int> Rabat
		{
			get
			{
				return this._Rabat;
			}
			set
			{
				if ((this._Rabat != value))
				{
					this.OnRabatChanging(value);
					this.SendPropertyChanging();
					this._Rabat = value;
					this.SendPropertyChanged("Rabat");
					this.OnRabatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaPosleRabata", DbType="Float")]
		public System.Nullable<double> CenaPosleRabata
		{
			get
			{
				return this._CenaPosleRabata;
			}
			set
			{
				if ((this._CenaPosleRabata != value))
				{
					this.OnCenaPosleRabataChanging(value);
					this.SendPropertyChanging();
					this._CenaPosleRabata = value;
					this.SendPropertyChanged("CenaPosleRabata");
					this.OnCenaPosleRabataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolicina", DbType="Int")]
		public System.Nullable<int> Kolicina
		{
			get
			{
				return this._Kolicina;
			}
			set
			{
				if ((this._Kolicina != value))
				{
					this.OnKolicinaChanging(value);
					this.SendPropertyChanging();
					this._Kolicina = value;
					this.SendPropertyChanged("Kolicina");
					this.OnKolicinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marza", DbType="Float")]
		public System.Nullable<double> Marza
		{
			get
			{
				return this._Marza;
			}
			set
			{
				if ((this._Marza != value))
				{
					this.OnMarzaChanging(value);
					this.SendPropertyChanging();
					this._Marza = value;
					this.SendPropertyChanged("Marza");
					this.OnMarzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUC", DbType="Float")]
		public System.Nullable<double> RUC
		{
			get
			{
				return this._RUC;
			}
			set
			{
				if ((this._RUC != value))
				{
					this.OnRUCChanging(value);
					this.SendPropertyChanging();
					this._RUC = value;
					this.SendPropertyChanged("RUC");
					this.OnRUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OsnovicaPoJM", DbType="Float")]
		public System.Nullable<double> OsnovicaPoJM
		{
			get
			{
				return this._OsnovicaPoJM;
			}
			set
			{
				if ((this._OsnovicaPoJM != value))
				{
					this.OnOsnovicaPoJMChanging(value);
					this.SendPropertyChanging();
					this._OsnovicaPoJM = value;
					this.SendPropertyChanged("OsnovicaPoJM");
					this.OnOsnovicaPoJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDVStopa", DbType="Int")]
		public System.Nullable<int> PDVStopa
		{
			get
			{
				return this._PDVStopa;
			}
			set
			{
				if ((this._PDVStopa != value))
				{
					this.OnPDVStopaChanging(value);
					this.SendPropertyChanging();
					this._PDVStopa = value;
					this.SendPropertyChanged("PDVStopa");
					this.OnPDVStopaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IznosPDVPoJM", DbType="Float")]
		public System.Nullable<double> IznosPDVPoJM
		{
			get
			{
				return this._IznosPDVPoJM;
			}
			set
			{
				if ((this._IznosPDVPoJM != value))
				{
					this.OnIznosPDVPoJMChanging(value);
					this.SendPropertyChanging();
					this._IznosPDVPoJM = value;
					this.SendPropertyChanged("IznosPDVPoJM");
					this.OnIznosPDVPoJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdajnaCena", DbType="Float")]
		public System.Nullable<double> ProdajnaCena
		{
			get
			{
				return this._ProdajnaCena;
			}
			set
			{
				if ((this._ProdajnaCena != value))
				{
					this.OnProdajnaCenaChanging(value);
					this.SendPropertyChanging();
					this._ProdajnaCena = value;
					this.SendPropertyChanged("ProdajnaCena");
					this.OnProdajnaCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Otpad", DbType="Int")]
		public System.Nullable<int> Otpad
		{
			get
			{
				return this._Otpad;
			}
			set
			{
				if ((this._Otpad != value))
				{
					this.OnOtpadChanging(value);
					this.SendPropertyChanging();
					this._Otpad = value;
					this.SendPropertyChanged("Otpad");
					this.OnOtpadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Artikal_FakturaStavka", Storage="_FakturaStavkas", ThisKey="SifraArtikla", OtherKey="SifraArtikla")]
		public EntitySet<FakturaStavka> FakturaStavkas
		{
			get
			{
				return this._FakturaStavkas;
			}
			set
			{
				this._FakturaStavkas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FakturaStavkas(FakturaStavka entity)
		{
			this.SendPropertyChanging();
			entity.Artikal = this;
		}
		
		private void detach_FakturaStavkas(FakturaStavka entity)
		{
			this.SendPropertyChanging();
			entity.Artikal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prodavnica")]
	public partial class Prodavnica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProdavnicaID;
		
		private string _NazivProdavnice;
		
		private string _AdresaProdavnice;
		
		private string _KontaktProdavnice;
		
		private string _SajtProdavnice;
		
		private string _MejlProdavnice;
		
		private int _PIBProdavnice;
		
		private int _MBProdavnice;
		
		private System.Nullable<int> _ProdavacID;
		
		private EntitySet<Faktura> _Fakturas;
		
		private EntityRef<Prodavac> _Prodavac;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProdavnicaIDChanging(int value);
    partial void OnProdavnicaIDChanged();
    partial void OnNazivProdavniceChanging(string value);
    partial void OnNazivProdavniceChanged();
    partial void OnAdresaProdavniceChanging(string value);
    partial void OnAdresaProdavniceChanged();
    partial void OnKontaktProdavniceChanging(string value);
    partial void OnKontaktProdavniceChanged();
    partial void OnSajtProdavniceChanging(string value);
    partial void OnSajtProdavniceChanged();
    partial void OnMejlProdavniceChanging(string value);
    partial void OnMejlProdavniceChanged();
    partial void OnPIBProdavniceChanging(int value);
    partial void OnPIBProdavniceChanged();
    partial void OnMBProdavniceChanging(int value);
    partial void OnMBProdavniceChanged();
    partial void OnProdavacIDChanging(System.Nullable<int> value);
    partial void OnProdavacIDChanged();
    #endregion
		
		public Prodavnica()
		{
			this._Fakturas = new EntitySet<Faktura>(new Action<Faktura>(this.attach_Fakturas), new Action<Faktura>(this.detach_Fakturas));
			this._Prodavac = default(EntityRef<Prodavac>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdavnicaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProdavnicaID
		{
			get
			{
				return this._ProdavnicaID;
			}
			set
			{
				if ((this._ProdavnicaID != value))
				{
					this.OnProdavnicaIDChanging(value);
					this.SendPropertyChanging();
					this._ProdavnicaID = value;
					this.SendPropertyChanged("ProdavnicaID");
					this.OnProdavnicaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivProdavnice", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NazivProdavnice
		{
			get
			{
				return this._NazivProdavnice;
			}
			set
			{
				if ((this._NazivProdavnice != value))
				{
					this.OnNazivProdavniceChanging(value);
					this.SendPropertyChanging();
					this._NazivProdavnice = value;
					this.SendPropertyChanged("NazivProdavnice");
					this.OnNazivProdavniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresaProdavnice", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string AdresaProdavnice
		{
			get
			{
				return this._AdresaProdavnice;
			}
			set
			{
				if ((this._AdresaProdavnice != value))
				{
					this.OnAdresaProdavniceChanging(value);
					this.SendPropertyChanging();
					this._AdresaProdavnice = value;
					this.SendPropertyChanged("AdresaProdavnice");
					this.OnAdresaProdavniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KontaktProdavnice", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KontaktProdavnice
		{
			get
			{
				return this._KontaktProdavnice;
			}
			set
			{
				if ((this._KontaktProdavnice != value))
				{
					this.OnKontaktProdavniceChanging(value);
					this.SendPropertyChanging();
					this._KontaktProdavnice = value;
					this.SendPropertyChanged("KontaktProdavnice");
					this.OnKontaktProdavniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SajtProdavnice", DbType="NVarChar(20)")]
		public string SajtProdavnice
		{
			get
			{
				return this._SajtProdavnice;
			}
			set
			{
				if ((this._SajtProdavnice != value))
				{
					this.OnSajtProdavniceChanging(value);
					this.SendPropertyChanging();
					this._SajtProdavnice = value;
					this.SendPropertyChanged("SajtProdavnice");
					this.OnSajtProdavniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MejlProdavnice", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MejlProdavnice
		{
			get
			{
				return this._MejlProdavnice;
			}
			set
			{
				if ((this._MejlProdavnice != value))
				{
					this.OnMejlProdavniceChanging(value);
					this.SendPropertyChanging();
					this._MejlProdavnice = value;
					this.SendPropertyChanged("MejlProdavnice");
					this.OnMejlProdavniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIBProdavnice", DbType="Int NOT NULL")]
		public int PIBProdavnice
		{
			get
			{
				return this._PIBProdavnice;
			}
			set
			{
				if ((this._PIBProdavnice != value))
				{
					this.OnPIBProdavniceChanging(value);
					this.SendPropertyChanging();
					this._PIBProdavnice = value;
					this.SendPropertyChanged("PIBProdavnice");
					this.OnPIBProdavniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBProdavnice", DbType="Int NOT NULL")]
		public int MBProdavnice
		{
			get
			{
				return this._MBProdavnice;
			}
			set
			{
				if ((this._MBProdavnice != value))
				{
					this.OnMBProdavniceChanging(value);
					this.SendPropertyChanging();
					this._MBProdavnice = value;
					this.SendPropertyChanged("MBProdavnice");
					this.OnMBProdavniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdavacID", DbType="Int")]
		public System.Nullable<int> ProdavacID
		{
			get
			{
				return this._ProdavacID;
			}
			set
			{
				if ((this._ProdavacID != value))
				{
					if (this._Prodavac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProdavacIDChanging(value);
					this.SendPropertyChanging();
					this._ProdavacID = value;
					this.SendPropertyChanged("ProdavacID");
					this.OnProdavacIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prodavnica_Faktura", Storage="_Fakturas", ThisKey="ProdavnicaID", OtherKey="ProdavnicaID")]
		public EntitySet<Faktura> Fakturas
		{
			get
			{
				return this._Fakturas;
			}
			set
			{
				this._Fakturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prodavac_Prodavnica", Storage="_Prodavac", ThisKey="ProdavacID", OtherKey="ProdavacID", IsForeignKey=true)]
		public Prodavac Prodavac
		{
			get
			{
				return this._Prodavac.Entity;
			}
			set
			{
				Prodavac previousValue = this._Prodavac.Entity;
				if (((previousValue != value) 
							|| (this._Prodavac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prodavac.Entity = null;
						previousValue.Prodavnicas.Remove(this);
					}
					this._Prodavac.Entity = value;
					if ((value != null))
					{
						value.Prodavnicas.Add(this);
						this._ProdavacID = value.ProdavacID;
					}
					else
					{
						this._ProdavacID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Prodavac");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fakturas(Faktura entity)
		{
			this.SendPropertyChanging();
			entity.Prodavnica = this;
		}
		
		private void detach_Fakturas(Faktura entity)
		{
			this.SendPropertyChanging();
			entity.Prodavnica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dobavljac")]
	public partial class Dobavljac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DobavljacID;
		
		private string _NazivDobavljaca;
		
		private string _Adresa;
		
		private string _PIB;
		
		private string _MaticniBroj;
		
		private string _Mejl;
		
		private string _Telefon;
		
		private string _PostanskiBroj;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDobavljacIDChanging(int value);
    partial void OnDobavljacIDChanged();
    partial void OnNazivDobavljacaChanging(string value);
    partial void OnNazivDobavljacaChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnPIBChanging(string value);
    partial void OnPIBChanged();
    partial void OnMaticniBrojChanging(string value);
    partial void OnMaticniBrojChanged();
    partial void OnMejlChanging(string value);
    partial void OnMejlChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnPostanskiBrojChanging(string value);
    partial void OnPostanskiBrojChanged();
    #endregion
		
		public Dobavljac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DobavljacID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DobavljacID
		{
			get
			{
				return this._DobavljacID;
			}
			set
			{
				if ((this._DobavljacID != value))
				{
					this.OnDobavljacIDChanging(value);
					this.SendPropertyChanging();
					this._DobavljacID = value;
					this.SendPropertyChanged("DobavljacID");
					this.OnDobavljacIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivDobavljaca", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivDobavljaca
		{
			get
			{
				return this._NazivDobavljaca;
			}
			set
			{
				if ((this._NazivDobavljaca != value))
				{
					this.OnNazivDobavljacaChanging(value);
					this.SendPropertyChanging();
					this._NazivDobavljaca = value;
					this.SendPropertyChanged("NazivDobavljaca");
					this.OnNazivDobavljacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="NVarChar(50)")]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIB", DbType="NVarChar(50)")]
		public string PIB
		{
			get
			{
				return this._PIB;
			}
			set
			{
				if ((this._PIB != value))
				{
					this.OnPIBChanging(value);
					this.SendPropertyChanging();
					this._PIB = value;
					this.SendPropertyChanged("PIB");
					this.OnPIBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaticniBroj", DbType="NVarChar(50)")]
		public string MaticniBroj
		{
			get
			{
				return this._MaticniBroj;
			}
			set
			{
				if ((this._MaticniBroj != value))
				{
					this.OnMaticniBrojChanging(value);
					this.SendPropertyChanging();
					this._MaticniBroj = value;
					this.SendPropertyChanged("MaticniBroj");
					this.OnMaticniBrojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mejl", DbType="NVarChar(100)")]
		public string Mejl
		{
			get
			{
				return this._Mejl;
			}
			set
			{
				if ((this._Mejl != value))
				{
					this.OnMejlChanging(value);
					this.SendPropertyChanging();
					this._Mejl = value;
					this.SendPropertyChanged("Mejl");
					this.OnMejlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(100)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostanskiBroj", DbType="NVarChar(50)")]
		public string PostanskiBroj
		{
			get
			{
				return this._PostanskiBroj;
			}
			set
			{
				if ((this._PostanskiBroj != value))
				{
					this.OnPostanskiBrojChanging(value);
					this.SendPropertyChanging();
					this._PostanskiBroj = value;
					this.SendPropertyChanged("PostanskiBroj");
					this.OnPostanskiBrojChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Faktura")]
	public partial class Faktura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FakturaID;
		
		private int _ProdavnicaID;
		
		private string _RacunBroj;
		
		private string _MestoIzdavanjaRacuna;
		
		private System.Nullable<System.DateTime> _DatumIzdavanjaRacuna;
		
		private System.Nullable<System.DateTime> _DatumPrometaDobara;
		
		private System.Nullable<System.DateTime> _RokPlacanja;
		
		private System.Nullable<double> _IznosRabata;
		
		private double _IznosBezRabata;
		
		private double _Ukupno;
		
		private string _NazivKupca;
		
		private EntitySet<FakturaStavka> _FakturaStavkas;
		
		private EntityRef<Prodavnica> _Prodavnica;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFakturaIDChanging(int value);
    partial void OnFakturaIDChanged();
    partial void OnProdavnicaIDChanging(int value);
    partial void OnProdavnicaIDChanged();
    partial void OnRacunBrojChanging(string value);
    partial void OnRacunBrojChanged();
    partial void OnMestoIzdavanjaRacunaChanging(string value);
    partial void OnMestoIzdavanjaRacunaChanged();
    partial void OnDatumIzdavanjaRacunaChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumIzdavanjaRacunaChanged();
    partial void OnDatumPrometaDobaraChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumPrometaDobaraChanged();
    partial void OnRokPlacanjaChanging(System.Nullable<System.DateTime> value);
    partial void OnRokPlacanjaChanged();
    partial void OnIznosRabataChanging(System.Nullable<double> value);
    partial void OnIznosRabataChanged();
    partial void OnIznosBezRabataChanging(double value);
    partial void OnIznosBezRabataChanged();
    partial void OnUkupnoChanging(double value);
    partial void OnUkupnoChanged();
    partial void OnNazivKupcaChanging(string value);
    partial void OnNazivKupcaChanged();
    #endregion
		
		public Faktura()
		{
			this._FakturaStavkas = new EntitySet<FakturaStavka>(new Action<FakturaStavka>(this.attach_FakturaStavkas), new Action<FakturaStavka>(this.detach_FakturaStavkas));
			this._Prodavnica = default(EntityRef<Prodavnica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakturaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FakturaID
		{
			get
			{
				return this._FakturaID;
			}
			set
			{
				if ((this._FakturaID != value))
				{
					this.OnFakturaIDChanging(value);
					this.SendPropertyChanging();
					this._FakturaID = value;
					this.SendPropertyChanged("FakturaID");
					this.OnFakturaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdavnicaID", DbType="Int NOT NULL")]
		public int ProdavnicaID
		{
			get
			{
				return this._ProdavnicaID;
			}
			set
			{
				if ((this._ProdavnicaID != value))
				{
					if (this._Prodavnica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProdavnicaIDChanging(value);
					this.SendPropertyChanging();
					this._ProdavnicaID = value;
					this.SendPropertyChanged("ProdavnicaID");
					this.OnProdavnicaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RacunBroj", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RacunBroj
		{
			get
			{
				return this._RacunBroj;
			}
			set
			{
				if ((this._RacunBroj != value))
				{
					this.OnRacunBrojChanging(value);
					this.SendPropertyChanging();
					this._RacunBroj = value;
					this.SendPropertyChanged("RacunBroj");
					this.OnRacunBrojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MestoIzdavanjaRacuna", DbType="NVarChar(50)")]
		public string MestoIzdavanjaRacuna
		{
			get
			{
				return this._MestoIzdavanjaRacuna;
			}
			set
			{
				if ((this._MestoIzdavanjaRacuna != value))
				{
					this.OnMestoIzdavanjaRacunaChanging(value);
					this.SendPropertyChanging();
					this._MestoIzdavanjaRacuna = value;
					this.SendPropertyChanged("MestoIzdavanjaRacuna");
					this.OnMestoIzdavanjaRacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumIzdavanjaRacuna", DbType="Date")]
		public System.Nullable<System.DateTime> DatumIzdavanjaRacuna
		{
			get
			{
				return this._DatumIzdavanjaRacuna;
			}
			set
			{
				if ((this._DatumIzdavanjaRacuna != value))
				{
					this.OnDatumIzdavanjaRacunaChanging(value);
					this.SendPropertyChanging();
					this._DatumIzdavanjaRacuna = value;
					this.SendPropertyChanged("DatumIzdavanjaRacuna");
					this.OnDatumIzdavanjaRacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumPrometaDobara", DbType="Date")]
		public System.Nullable<System.DateTime> DatumPrometaDobara
		{
			get
			{
				return this._DatumPrometaDobara;
			}
			set
			{
				if ((this._DatumPrometaDobara != value))
				{
					this.OnDatumPrometaDobaraChanging(value);
					this.SendPropertyChanging();
					this._DatumPrometaDobara = value;
					this.SendPropertyChanged("DatumPrometaDobara");
					this.OnDatumPrometaDobaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RokPlacanja", DbType="Date")]
		public System.Nullable<System.DateTime> RokPlacanja
		{
			get
			{
				return this._RokPlacanja;
			}
			set
			{
				if ((this._RokPlacanja != value))
				{
					this.OnRokPlacanjaChanging(value);
					this.SendPropertyChanging();
					this._RokPlacanja = value;
					this.SendPropertyChanged("RokPlacanja");
					this.OnRokPlacanjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IznosRabata", DbType="Float")]
		public System.Nullable<double> IznosRabata
		{
			get
			{
				return this._IznosRabata;
			}
			set
			{
				if ((this._IznosRabata != value))
				{
					this.OnIznosRabataChanging(value);
					this.SendPropertyChanging();
					this._IznosRabata = value;
					this.SendPropertyChanged("IznosRabata");
					this.OnIznosRabataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IznosBezRabata", DbType="Float NOT NULL")]
		public double IznosBezRabata
		{
			get
			{
				return this._IznosBezRabata;
			}
			set
			{
				if ((this._IznosBezRabata != value))
				{
					this.OnIznosBezRabataChanging(value);
					this.SendPropertyChanging();
					this._IznosBezRabata = value;
					this.SendPropertyChanged("IznosBezRabata");
					this.OnIznosBezRabataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ukupno", DbType="Float NOT NULL")]
		public double Ukupno
		{
			get
			{
				return this._Ukupno;
			}
			set
			{
				if ((this._Ukupno != value))
				{
					this.OnUkupnoChanging(value);
					this.SendPropertyChanging();
					this._Ukupno = value;
					this.SendPropertyChanged("Ukupno");
					this.OnUkupnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivKupca", DbType="NVarChar(50)")]
		public string NazivKupca
		{
			get
			{
				return this._NazivKupca;
			}
			set
			{
				if ((this._NazivKupca != value))
				{
					this.OnNazivKupcaChanging(value);
					this.SendPropertyChanging();
					this._NazivKupca = value;
					this.SendPropertyChanged("NazivKupca");
					this.OnNazivKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Faktura_FakturaStavka", Storage="_FakturaStavkas", ThisKey="FakturaID", OtherKey="FakturaID")]
		public EntitySet<FakturaStavka> FakturaStavkas
		{
			get
			{
				return this._FakturaStavkas;
			}
			set
			{
				this._FakturaStavkas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prodavnica_Faktura", Storage="_Prodavnica", ThisKey="ProdavnicaID", OtherKey="ProdavnicaID", IsForeignKey=true)]
		public Prodavnica Prodavnica
		{
			get
			{
				return this._Prodavnica.Entity;
			}
			set
			{
				Prodavnica previousValue = this._Prodavnica.Entity;
				if (((previousValue != value) 
							|| (this._Prodavnica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prodavnica.Entity = null;
						previousValue.Fakturas.Remove(this);
					}
					this._Prodavnica.Entity = value;
					if ((value != null))
					{
						value.Fakturas.Add(this);
						this._ProdavnicaID = value.ProdavnicaID;
					}
					else
					{
						this._ProdavnicaID = default(int);
					}
					this.SendPropertyChanged("Prodavnica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FakturaStavkas(FakturaStavka entity)
		{
			this.SendPropertyChanging();
			entity.Faktura = this;
		}
		
		private void detach_FakturaStavkas(FakturaStavka entity)
		{
			this.SendPropertyChanging();
			entity.Faktura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FakturaStavka")]
	public partial class FakturaStavka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StavkaID;
		
		private int _FakturaID;
		
		private string _SifraArtikla;
		
		private int _KolicinaStavke;
		
		private System.Nullable<double> _Rabat;
		
		private System.Nullable<double> _PoreskaOsnovica;
		
		private System.Nullable<double> _PDVStopa;
		
		private System.Nullable<double> _PDVIznos;
		
		private double _Ukupno;
		
		private EntityRef<Artikal> _Artikal;
		
		private EntityRef<Faktura> _Faktura;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStavkaIDChanging(int value);
    partial void OnStavkaIDChanged();
    partial void OnFakturaIDChanging(int value);
    partial void OnFakturaIDChanged();
    partial void OnSifraArtiklaChanging(string value);
    partial void OnSifraArtiklaChanged();
    partial void OnKolicinaStavkeChanging(int value);
    partial void OnKolicinaStavkeChanged();
    partial void OnRabatChanging(System.Nullable<double> value);
    partial void OnRabatChanged();
    partial void OnPoreskaOsnovicaChanging(System.Nullable<double> value);
    partial void OnPoreskaOsnovicaChanged();
    partial void OnPDVStopaChanging(System.Nullable<double> value);
    partial void OnPDVStopaChanged();
    partial void OnPDVIznosChanging(System.Nullable<double> value);
    partial void OnPDVIznosChanged();
    partial void OnUkupnoChanging(double value);
    partial void OnUkupnoChanged();
    #endregion
		
		public FakturaStavka()
		{
			this._Artikal = default(EntityRef<Artikal>);
			this._Faktura = default(EntityRef<Faktura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StavkaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StavkaID
		{
			get
			{
				return this._StavkaID;
			}
			set
			{
				if ((this._StavkaID != value))
				{
					this.OnStavkaIDChanging(value);
					this.SendPropertyChanging();
					this._StavkaID = value;
					this.SendPropertyChanged("StavkaID");
					this.OnStavkaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakturaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FakturaID
		{
			get
			{
				return this._FakturaID;
			}
			set
			{
				if ((this._FakturaID != value))
				{
					if (this._Faktura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFakturaIDChanging(value);
					this.SendPropertyChanging();
					this._FakturaID = value;
					this.SendPropertyChanged("FakturaID");
					this.OnFakturaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraArtikla", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SifraArtikla
		{
			get
			{
				return this._SifraArtikla;
			}
			set
			{
				if ((this._SifraArtikla != value))
				{
					if (this._Artikal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSifraArtiklaChanging(value);
					this.SendPropertyChanging();
					this._SifraArtikla = value;
					this.SendPropertyChanged("SifraArtikla");
					this.OnSifraArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KolicinaStavke", DbType="Int NOT NULL")]
		public int KolicinaStavke
		{
			get
			{
				return this._KolicinaStavke;
			}
			set
			{
				if ((this._KolicinaStavke != value))
				{
					this.OnKolicinaStavkeChanging(value);
					this.SendPropertyChanging();
					this._KolicinaStavke = value;
					this.SendPropertyChanged("KolicinaStavke");
					this.OnKolicinaStavkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rabat", DbType="Float")]
		public System.Nullable<double> Rabat
		{
			get
			{
				return this._Rabat;
			}
			set
			{
				if ((this._Rabat != value))
				{
					this.OnRabatChanging(value);
					this.SendPropertyChanging();
					this._Rabat = value;
					this.SendPropertyChanged("Rabat");
					this.OnRabatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoreskaOsnovica", DbType="Float")]
		public System.Nullable<double> PoreskaOsnovica
		{
			get
			{
				return this._PoreskaOsnovica;
			}
			set
			{
				if ((this._PoreskaOsnovica != value))
				{
					this.OnPoreskaOsnovicaChanging(value);
					this.SendPropertyChanging();
					this._PoreskaOsnovica = value;
					this.SendPropertyChanged("PoreskaOsnovica");
					this.OnPoreskaOsnovicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDVStopa", DbType="Float")]
		public System.Nullable<double> PDVStopa
		{
			get
			{
				return this._PDVStopa;
			}
			set
			{
				if ((this._PDVStopa != value))
				{
					this.OnPDVStopaChanging(value);
					this.SendPropertyChanging();
					this._PDVStopa = value;
					this.SendPropertyChanged("PDVStopa");
					this.OnPDVStopaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDVIznos", DbType="Float")]
		public System.Nullable<double> PDVIznos
		{
			get
			{
				return this._PDVIznos;
			}
			set
			{
				if ((this._PDVIznos != value))
				{
					this.OnPDVIznosChanging(value);
					this.SendPropertyChanging();
					this._PDVIznos = value;
					this.SendPropertyChanged("PDVIznos");
					this.OnPDVIznosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ukupno", DbType="Float NOT NULL")]
		public double Ukupno
		{
			get
			{
				return this._Ukupno;
			}
			set
			{
				if ((this._Ukupno != value))
				{
					this.OnUkupnoChanging(value);
					this.SendPropertyChanging();
					this._Ukupno = value;
					this.SendPropertyChanged("Ukupno");
					this.OnUkupnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Artikal_FakturaStavka", Storage="_Artikal", ThisKey="SifraArtikla", OtherKey="SifraArtikla", IsForeignKey=true)]
		public Artikal Artikal
		{
			get
			{
				return this._Artikal.Entity;
			}
			set
			{
				Artikal previousValue = this._Artikal.Entity;
				if (((previousValue != value) 
							|| (this._Artikal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Artikal.Entity = null;
						previousValue.FakturaStavkas.Remove(this);
					}
					this._Artikal.Entity = value;
					if ((value != null))
					{
						value.FakturaStavkas.Add(this);
						this._SifraArtikla = value.SifraArtikla;
					}
					else
					{
						this._SifraArtikla = default(string);
					}
					this.SendPropertyChanged("Artikal");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Faktura_FakturaStavka", Storage="_Faktura", ThisKey="FakturaID", OtherKey="FakturaID", IsForeignKey=true)]
		public Faktura Faktura
		{
			get
			{
				return this._Faktura.Entity;
			}
			set
			{
				Faktura previousValue = this._Faktura.Entity;
				if (((previousValue != value) 
							|| (this._Faktura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Faktura.Entity = null;
						previousValue.FakturaStavkas.Remove(this);
					}
					this._Faktura.Entity = value;
					if ((value != null))
					{
						value.FakturaStavkas.Add(this);
						this._FakturaID = value.FakturaID;
					}
					else
					{
						this._FakturaID = default(int);
					}
					this.SendPropertyChanged("Faktura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kalkulacija")]
	public partial class Kalkulacija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KalkulacijaID;
		
		private string _SifraArtikla;
		
		private System.Nullable<double> _NabavnaCenaINO;
		
		private System.Nullable<double> _NabavnaCenaRSD;
		
		private System.Nullable<int> _Kolicina;
		
		private System.Nullable<double> _Vrednost;
		
		private System.Nullable<double> _BrutoVrednostUkupno;
		
		private System.Nullable<double> _BrutoVrednostPoJM;
		
		private System.Nullable<double> _Marza;
		
		private System.Nullable<double> _RUC;
		
		private System.Nullable<double> _OsnovicaPoJM;
		
		private System.Nullable<int> _PDVStopa;
		
		private System.Nullable<double> _IznosPDVpoJM;
		
		private System.Nullable<double> _ProdajnaCena;
		
		private System.Nullable<double> _OsnovicaUkupno;
		
		private System.Nullable<double> _IznosPDVUkupno;
		
		private System.Nullable<double> _ProdajnaVrednostUkupno;
		
		private System.Nullable<double> _RUCUkupno;
		
		private System.Nullable<double> _Kurs;
		
		private System.Nullable<System.DateTime> _DatumKalkulacije;
		
		private System.Nullable<int> _DobavljacID;
		
		private string _BrojDokumenta;
		
		private System.Nullable<double> _UkupniTroskovi;
		
		private string _NazivArtikla;
		
		private System.Nullable<double> _TroskoviPoJM;
		
		private System.Nullable<int> _BrojKalkulacije;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKalkulacijaIDChanging(int value);
    partial void OnKalkulacijaIDChanged();
    partial void OnSifraArtiklaChanging(string value);
    partial void OnSifraArtiklaChanged();
    partial void OnNabavnaCenaINOChanging(System.Nullable<double> value);
    partial void OnNabavnaCenaINOChanged();
    partial void OnNabavnaCenaRSDChanging(System.Nullable<double> value);
    partial void OnNabavnaCenaRSDChanged();
    partial void OnKolicinaChanging(System.Nullable<int> value);
    partial void OnKolicinaChanged();
    partial void OnVrednostChanging(System.Nullable<double> value);
    partial void OnVrednostChanged();
    partial void OnBrutoVrednostUkupnoChanging(System.Nullable<double> value);
    partial void OnBrutoVrednostUkupnoChanged();
    partial void OnBrutoVrednostPoJMChanging(System.Nullable<double> value);
    partial void OnBrutoVrednostPoJMChanged();
    partial void OnMarzaChanging(System.Nullable<double> value);
    partial void OnMarzaChanged();
    partial void OnRUCChanging(System.Nullable<double> value);
    partial void OnRUCChanged();
    partial void OnOsnovicaPoJMChanging(System.Nullable<double> value);
    partial void OnOsnovicaPoJMChanged();
    partial void OnPDVStopaChanging(System.Nullable<int> value);
    partial void OnPDVStopaChanged();
    partial void OnIznosPDVpoJMChanging(System.Nullable<double> value);
    partial void OnIznosPDVpoJMChanged();
    partial void OnProdajnaCenaChanging(System.Nullable<double> value);
    partial void OnProdajnaCenaChanged();
    partial void OnOsnovicaUkupnoChanging(System.Nullable<double> value);
    partial void OnOsnovicaUkupnoChanged();
    partial void OnIznosPDVUkupnoChanging(System.Nullable<double> value);
    partial void OnIznosPDVUkupnoChanged();
    partial void OnProdajnaVrednostUkupnoChanging(System.Nullable<double> value);
    partial void OnProdajnaVrednostUkupnoChanged();
    partial void OnRUCUkupnoChanging(System.Nullable<double> value);
    partial void OnRUCUkupnoChanged();
    partial void OnKursChanging(System.Nullable<double> value);
    partial void OnKursChanged();
    partial void OnDatumKalkulacijeChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumKalkulacijeChanged();
    partial void OnDobavljacIDChanging(System.Nullable<int> value);
    partial void OnDobavljacIDChanged();
    partial void OnBrojDokumentaChanging(string value);
    partial void OnBrojDokumentaChanged();
    partial void OnUkupniTroskoviChanging(System.Nullable<double> value);
    partial void OnUkupniTroskoviChanged();
    partial void OnNazivArtiklaChanging(string value);
    partial void OnNazivArtiklaChanged();
    partial void OnTroskoviPoJMChanging(System.Nullable<double> value);
    partial void OnTroskoviPoJMChanged();
    partial void OnBrojKalkulacijeChanging(System.Nullable<int> value);
    partial void OnBrojKalkulacijeChanged();
    #endregion
		
		public Kalkulacija()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KalkulacijaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KalkulacijaID
		{
			get
			{
				return this._KalkulacijaID;
			}
			set
			{
				if ((this._KalkulacijaID != value))
				{
					this.OnKalkulacijaIDChanging(value);
					this.SendPropertyChanging();
					this._KalkulacijaID = value;
					this.SendPropertyChanged("KalkulacijaID");
					this.OnKalkulacijaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraArtikla", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SifraArtikla
		{
			get
			{
				return this._SifraArtikla;
			}
			set
			{
				if ((this._SifraArtikla != value))
				{
					this.OnSifraArtiklaChanging(value);
					this.SendPropertyChanging();
					this._SifraArtikla = value;
					this.SendPropertyChanged("SifraArtikla");
					this.OnSifraArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NabavnaCenaINO", DbType="Float")]
		public System.Nullable<double> NabavnaCenaINO
		{
			get
			{
				return this._NabavnaCenaINO;
			}
			set
			{
				if ((this._NabavnaCenaINO != value))
				{
					this.OnNabavnaCenaINOChanging(value);
					this.SendPropertyChanging();
					this._NabavnaCenaINO = value;
					this.SendPropertyChanged("NabavnaCenaINO");
					this.OnNabavnaCenaINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NabavnaCenaRSD", DbType="Float")]
		public System.Nullable<double> NabavnaCenaRSD
		{
			get
			{
				return this._NabavnaCenaRSD;
			}
			set
			{
				if ((this._NabavnaCenaRSD != value))
				{
					this.OnNabavnaCenaRSDChanging(value);
					this.SendPropertyChanging();
					this._NabavnaCenaRSD = value;
					this.SendPropertyChanged("NabavnaCenaRSD");
					this.OnNabavnaCenaRSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolicina", DbType="Int")]
		public System.Nullable<int> Kolicina
		{
			get
			{
				return this._Kolicina;
			}
			set
			{
				if ((this._Kolicina != value))
				{
					this.OnKolicinaChanging(value);
					this.SendPropertyChanging();
					this._Kolicina = value;
					this.SendPropertyChanged("Kolicina");
					this.OnKolicinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vrednost", DbType="Float")]
		public System.Nullable<double> Vrednost
		{
			get
			{
				return this._Vrednost;
			}
			set
			{
				if ((this._Vrednost != value))
				{
					this.OnVrednostChanging(value);
					this.SendPropertyChanging();
					this._Vrednost = value;
					this.SendPropertyChanged("Vrednost");
					this.OnVrednostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrutoVrednostUkupno", DbType="Float")]
		public System.Nullable<double> BrutoVrednostUkupno
		{
			get
			{
				return this._BrutoVrednostUkupno;
			}
			set
			{
				if ((this._BrutoVrednostUkupno != value))
				{
					this.OnBrutoVrednostUkupnoChanging(value);
					this.SendPropertyChanging();
					this._BrutoVrednostUkupno = value;
					this.SendPropertyChanged("BrutoVrednostUkupno");
					this.OnBrutoVrednostUkupnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrutoVrednostPoJM", DbType="Float")]
		public System.Nullable<double> BrutoVrednostPoJM
		{
			get
			{
				return this._BrutoVrednostPoJM;
			}
			set
			{
				if ((this._BrutoVrednostPoJM != value))
				{
					this.OnBrutoVrednostPoJMChanging(value);
					this.SendPropertyChanging();
					this._BrutoVrednostPoJM = value;
					this.SendPropertyChanged("BrutoVrednostPoJM");
					this.OnBrutoVrednostPoJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marza", DbType="Float")]
		public System.Nullable<double> Marza
		{
			get
			{
				return this._Marza;
			}
			set
			{
				if ((this._Marza != value))
				{
					this.OnMarzaChanging(value);
					this.SendPropertyChanging();
					this._Marza = value;
					this.SendPropertyChanged("Marza");
					this.OnMarzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUC", DbType="Float")]
		public System.Nullable<double> RUC
		{
			get
			{
				return this._RUC;
			}
			set
			{
				if ((this._RUC != value))
				{
					this.OnRUCChanging(value);
					this.SendPropertyChanging();
					this._RUC = value;
					this.SendPropertyChanged("RUC");
					this.OnRUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OsnovicaPoJM", DbType="Float")]
		public System.Nullable<double> OsnovicaPoJM
		{
			get
			{
				return this._OsnovicaPoJM;
			}
			set
			{
				if ((this._OsnovicaPoJM != value))
				{
					this.OnOsnovicaPoJMChanging(value);
					this.SendPropertyChanging();
					this._OsnovicaPoJM = value;
					this.SendPropertyChanged("OsnovicaPoJM");
					this.OnOsnovicaPoJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDVStopa", DbType="Int")]
		public System.Nullable<int> PDVStopa
		{
			get
			{
				return this._PDVStopa;
			}
			set
			{
				if ((this._PDVStopa != value))
				{
					this.OnPDVStopaChanging(value);
					this.SendPropertyChanging();
					this._PDVStopa = value;
					this.SendPropertyChanged("PDVStopa");
					this.OnPDVStopaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IznosPDVpoJM", DbType="Float")]
		public System.Nullable<double> IznosPDVpoJM
		{
			get
			{
				return this._IznosPDVpoJM;
			}
			set
			{
				if ((this._IznosPDVpoJM != value))
				{
					this.OnIznosPDVpoJMChanging(value);
					this.SendPropertyChanging();
					this._IznosPDVpoJM = value;
					this.SendPropertyChanged("IznosPDVpoJM");
					this.OnIznosPDVpoJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdajnaCena", DbType="Float")]
		public System.Nullable<double> ProdajnaCena
		{
			get
			{
				return this._ProdajnaCena;
			}
			set
			{
				if ((this._ProdajnaCena != value))
				{
					this.OnProdajnaCenaChanging(value);
					this.SendPropertyChanging();
					this._ProdajnaCena = value;
					this.SendPropertyChanged("ProdajnaCena");
					this.OnProdajnaCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OsnovicaUkupno", DbType="Float")]
		public System.Nullable<double> OsnovicaUkupno
		{
			get
			{
				return this._OsnovicaUkupno;
			}
			set
			{
				if ((this._OsnovicaUkupno != value))
				{
					this.OnOsnovicaUkupnoChanging(value);
					this.SendPropertyChanging();
					this._OsnovicaUkupno = value;
					this.SendPropertyChanged("OsnovicaUkupno");
					this.OnOsnovicaUkupnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IznosPDVUkupno", DbType="Float")]
		public System.Nullable<double> IznosPDVUkupno
		{
			get
			{
				return this._IznosPDVUkupno;
			}
			set
			{
				if ((this._IznosPDVUkupno != value))
				{
					this.OnIznosPDVUkupnoChanging(value);
					this.SendPropertyChanging();
					this._IznosPDVUkupno = value;
					this.SendPropertyChanged("IznosPDVUkupno");
					this.OnIznosPDVUkupnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdajnaVrednostUkupno", DbType="Float")]
		public System.Nullable<double> ProdajnaVrednostUkupno
		{
			get
			{
				return this._ProdajnaVrednostUkupno;
			}
			set
			{
				if ((this._ProdajnaVrednostUkupno != value))
				{
					this.OnProdajnaVrednostUkupnoChanging(value);
					this.SendPropertyChanging();
					this._ProdajnaVrednostUkupno = value;
					this.SendPropertyChanged("ProdajnaVrednostUkupno");
					this.OnProdajnaVrednostUkupnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUCUkupno", DbType="Float")]
		public System.Nullable<double> RUCUkupno
		{
			get
			{
				return this._RUCUkupno;
			}
			set
			{
				if ((this._RUCUkupno != value))
				{
					this.OnRUCUkupnoChanging(value);
					this.SendPropertyChanging();
					this._RUCUkupno = value;
					this.SendPropertyChanged("RUCUkupno");
					this.OnRUCUkupnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kurs", DbType="Float")]
		public System.Nullable<double> Kurs
		{
			get
			{
				return this._Kurs;
			}
			set
			{
				if ((this._Kurs != value))
				{
					this.OnKursChanging(value);
					this.SendPropertyChanging();
					this._Kurs = value;
					this.SendPropertyChanged("Kurs");
					this.OnKursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumKalkulacije", DbType="Date")]
		public System.Nullable<System.DateTime> DatumKalkulacije
		{
			get
			{
				return this._DatumKalkulacije;
			}
			set
			{
				if ((this._DatumKalkulacije != value))
				{
					this.OnDatumKalkulacijeChanging(value);
					this.SendPropertyChanging();
					this._DatumKalkulacije = value;
					this.SendPropertyChanged("DatumKalkulacije");
					this.OnDatumKalkulacijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DobavljacID", DbType="Int")]
		public System.Nullable<int> DobavljacID
		{
			get
			{
				return this._DobavljacID;
			}
			set
			{
				if ((this._DobavljacID != value))
				{
					this.OnDobavljacIDChanging(value);
					this.SendPropertyChanging();
					this._DobavljacID = value;
					this.SendPropertyChanged("DobavljacID");
					this.OnDobavljacIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrojDokumenta", DbType="NVarChar(50)")]
		public string BrojDokumenta
		{
			get
			{
				return this._BrojDokumenta;
			}
			set
			{
				if ((this._BrojDokumenta != value))
				{
					this.OnBrojDokumentaChanging(value);
					this.SendPropertyChanging();
					this._BrojDokumenta = value;
					this.SendPropertyChanged("BrojDokumenta");
					this.OnBrojDokumentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UkupniTroskovi", DbType="Float")]
		public System.Nullable<double> UkupniTroskovi
		{
			get
			{
				return this._UkupniTroskovi;
			}
			set
			{
				if ((this._UkupniTroskovi != value))
				{
					this.OnUkupniTroskoviChanging(value);
					this.SendPropertyChanging();
					this._UkupniTroskovi = value;
					this.SendPropertyChanged("UkupniTroskovi");
					this.OnUkupniTroskoviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivArtikla", DbType="NVarChar(50)")]
		public string NazivArtikla
		{
			get
			{
				return this._NazivArtikla;
			}
			set
			{
				if ((this._NazivArtikla != value))
				{
					this.OnNazivArtiklaChanging(value);
					this.SendPropertyChanging();
					this._NazivArtikla = value;
					this.SendPropertyChanged("NazivArtikla");
					this.OnNazivArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TroskoviPoJM", DbType="Float")]
		public System.Nullable<double> TroskoviPoJM
		{
			get
			{
				return this._TroskoviPoJM;
			}
			set
			{
				if ((this._TroskoviPoJM != value))
				{
					this.OnTroskoviPoJMChanging(value);
					this.SendPropertyChanging();
					this._TroskoviPoJM = value;
					this.SendPropertyChanged("TroskoviPoJM");
					this.OnTroskoviPoJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrojKalkulacije", DbType="Int")]
		public System.Nullable<int> BrojKalkulacije
		{
			get
			{
				return this._BrojKalkulacije;
			}
			set
			{
				if ((this._BrojKalkulacije != value))
				{
					this.OnBrojKalkulacijeChanging(value);
					this.SendPropertyChanging();
					this._BrojKalkulacije = value;
					this.SendPropertyChanged("BrojKalkulacije");
					this.OnBrojKalkulacijeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kupac")]
	public partial class Kupac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KupacID;
		
		private string _NazivKupca;
		
		private string _AdresaKupca;
		
		private string _KontaktKupca;
		
		private string _SajtKupca;
		
		private string _MejlKupca;
		
		private string _PostanskiBrKupca;
		
		private System.Nullable<int> _PIBKupca;
		
		private System.Nullable<int> _MBKupca;
		
		private bool _DaLiJeFirma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKupacIDChanging(int value);
    partial void OnKupacIDChanged();
    partial void OnNazivKupcaChanging(string value);
    partial void OnNazivKupcaChanged();
    partial void OnAdresaKupcaChanging(string value);
    partial void OnAdresaKupcaChanged();
    partial void OnKontaktKupcaChanging(string value);
    partial void OnKontaktKupcaChanged();
    partial void OnSajtKupcaChanging(string value);
    partial void OnSajtKupcaChanged();
    partial void OnMejlKupcaChanging(string value);
    partial void OnMejlKupcaChanged();
    partial void OnPostanskiBrKupcaChanging(string value);
    partial void OnPostanskiBrKupcaChanged();
    partial void OnPIBKupcaChanging(System.Nullable<int> value);
    partial void OnPIBKupcaChanged();
    partial void OnMBKupcaChanging(System.Nullable<int> value);
    partial void OnMBKupcaChanged();
    partial void OnDaLiJeFirmaChanging(bool value);
    partial void OnDaLiJeFirmaChanged();
    #endregion
		
		public Kupac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KupacID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KupacID
		{
			get
			{
				return this._KupacID;
			}
			set
			{
				if ((this._KupacID != value))
				{
					this.OnKupacIDChanging(value);
					this.SendPropertyChanging();
					this._KupacID = value;
					this.SendPropertyChanged("KupacID");
					this.OnKupacIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivKupca", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NazivKupca
		{
			get
			{
				return this._NazivKupca;
			}
			set
			{
				if ((this._NazivKupca != value))
				{
					this.OnNazivKupcaChanging(value);
					this.SendPropertyChanging();
					this._NazivKupca = value;
					this.SendPropertyChanged("NazivKupca");
					this.OnNazivKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresaKupca", DbType="NVarChar(50)")]
		public string AdresaKupca
		{
			get
			{
				return this._AdresaKupca;
			}
			set
			{
				if ((this._AdresaKupca != value))
				{
					this.OnAdresaKupcaChanging(value);
					this.SendPropertyChanging();
					this._AdresaKupca = value;
					this.SendPropertyChanged("AdresaKupca");
					this.OnAdresaKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KontaktKupca", DbType="NVarChar(20)")]
		public string KontaktKupca
		{
			get
			{
				return this._KontaktKupca;
			}
			set
			{
				if ((this._KontaktKupca != value))
				{
					this.OnKontaktKupcaChanging(value);
					this.SendPropertyChanging();
					this._KontaktKupca = value;
					this.SendPropertyChanged("KontaktKupca");
					this.OnKontaktKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SajtKupca", DbType="NVarChar(50)")]
		public string SajtKupca
		{
			get
			{
				return this._SajtKupca;
			}
			set
			{
				if ((this._SajtKupca != value))
				{
					this.OnSajtKupcaChanging(value);
					this.SendPropertyChanging();
					this._SajtKupca = value;
					this.SendPropertyChanged("SajtKupca");
					this.OnSajtKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MejlKupca", DbType="NVarChar(50)")]
		public string MejlKupca
		{
			get
			{
				return this._MejlKupca;
			}
			set
			{
				if ((this._MejlKupca != value))
				{
					this.OnMejlKupcaChanging(value);
					this.SendPropertyChanging();
					this._MejlKupca = value;
					this.SendPropertyChanged("MejlKupca");
					this.OnMejlKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostanskiBrKupca", DbType="NVarChar(10)")]
		public string PostanskiBrKupca
		{
			get
			{
				return this._PostanskiBrKupca;
			}
			set
			{
				if ((this._PostanskiBrKupca != value))
				{
					this.OnPostanskiBrKupcaChanging(value);
					this.SendPropertyChanging();
					this._PostanskiBrKupca = value;
					this.SendPropertyChanged("PostanskiBrKupca");
					this.OnPostanskiBrKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIBKupca", DbType="Int")]
		public System.Nullable<int> PIBKupca
		{
			get
			{
				return this._PIBKupca;
			}
			set
			{
				if ((this._PIBKupca != value))
				{
					this.OnPIBKupcaChanging(value);
					this.SendPropertyChanging();
					this._PIBKupca = value;
					this.SendPropertyChanged("PIBKupca");
					this.OnPIBKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBKupca", DbType="Int")]
		public System.Nullable<int> MBKupca
		{
			get
			{
				return this._MBKupca;
			}
			set
			{
				if ((this._MBKupca != value))
				{
					this.OnMBKupcaChanging(value);
					this.SendPropertyChanging();
					this._MBKupca = value;
					this.SendPropertyChanged("MBKupca");
					this.OnMBKupcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaLiJeFirma", DbType="Bit NOT NULL")]
		public bool DaLiJeFirma
		{
			get
			{
				return this._DaLiJeFirma;
			}
			set
			{
				if ((this._DaLiJeFirma != value))
				{
					this.OnDaLiJeFirmaChanging(value);
					this.SendPropertyChanging();
					this._DaLiJeFirma = value;
					this.SendPropertyChanged("DaLiJeFirma");
					this.OnDaLiJeFirmaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nivelacije")]
	public partial class Nivelacije : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NivelacijaID;
		
		private string _SifraArtikla;
		
		private string _NazivArtikla;
		
		private System.Nullable<int> _Kolicina;
		
		private System.Nullable<double> _StaraCena;
		
		private System.Nullable<double> _NovaProdajnaCena;
		
		private System.Nullable<double> _NivelacijaPoJM;
		
		private System.Nullable<double> _StaraOsnovica;
		
		private System.Nullable<double> _StariPDV;
		
		private System.Nullable<double> _NovaOsnovica;
		
		private System.Nullable<double> _NoviPDV;
		
		private System.Nullable<double> _StaraMarza;
		
		private System.Nullable<double> _NovaMarza;
		
		private System.Nullable<System.DateTime> _DatumNivelacije;
		
		private System.Nullable<double> _StaraRUC;
		
		private System.Nullable<double> _NovaRUC;
		
		private System.Nullable<int> _BrojNivelacije;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNivelacijaIDChanging(int value);
    partial void OnNivelacijaIDChanged();
    partial void OnSifraArtiklaChanging(string value);
    partial void OnSifraArtiklaChanged();
    partial void OnNazivArtiklaChanging(string value);
    partial void OnNazivArtiklaChanged();
    partial void OnKolicinaChanging(System.Nullable<int> value);
    partial void OnKolicinaChanged();
    partial void OnStaraCenaChanging(System.Nullable<double> value);
    partial void OnStaraCenaChanged();
    partial void OnNovaProdajnaCenaChanging(System.Nullable<double> value);
    partial void OnNovaProdajnaCenaChanged();
    partial void OnNivelacijaPoJMChanging(System.Nullable<double> value);
    partial void OnNivelacijaPoJMChanged();
    partial void OnStaraOsnovicaChanging(System.Nullable<double> value);
    partial void OnStaraOsnovicaChanged();
    partial void OnStariPDVChanging(System.Nullable<double> value);
    partial void OnStariPDVChanged();
    partial void OnNovaOsnovicaChanging(System.Nullable<double> value);
    partial void OnNovaOsnovicaChanged();
    partial void OnNoviPDVChanging(System.Nullable<double> value);
    partial void OnNoviPDVChanged();
    partial void OnStaraMarzaChanging(System.Nullable<double> value);
    partial void OnStaraMarzaChanged();
    partial void OnNovaMarzaChanging(System.Nullable<double> value);
    partial void OnNovaMarzaChanged();
    partial void OnDatumNivelacijeChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumNivelacijeChanged();
    partial void OnStaraRUCChanging(System.Nullable<double> value);
    partial void OnStaraRUCChanged();
    partial void OnNovaRUCChanging(System.Nullable<double> value);
    partial void OnNovaRUCChanged();
    partial void OnBrojNivelacijeChanging(System.Nullable<int> value);
    partial void OnBrojNivelacijeChanged();
    #endregion
		
		public Nivelacije()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelacijaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NivelacijaID
		{
			get
			{
				return this._NivelacijaID;
			}
			set
			{
				if ((this._NivelacijaID != value))
				{
					this.OnNivelacijaIDChanging(value);
					this.SendPropertyChanging();
					this._NivelacijaID = value;
					this.SendPropertyChanged("NivelacijaID");
					this.OnNivelacijaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraArtikla", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SifraArtikla
		{
			get
			{
				return this._SifraArtikla;
			}
			set
			{
				if ((this._SifraArtikla != value))
				{
					this.OnSifraArtiklaChanging(value);
					this.SendPropertyChanging();
					this._SifraArtikla = value;
					this.SendPropertyChanged("SifraArtikla");
					this.OnSifraArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivArtikla", DbType="NVarChar(50)")]
		public string NazivArtikla
		{
			get
			{
				return this._NazivArtikla;
			}
			set
			{
				if ((this._NazivArtikla != value))
				{
					this.OnNazivArtiklaChanging(value);
					this.SendPropertyChanging();
					this._NazivArtikla = value;
					this.SendPropertyChanged("NazivArtikla");
					this.OnNazivArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolicina", DbType="Int")]
		public System.Nullable<int> Kolicina
		{
			get
			{
				return this._Kolicina;
			}
			set
			{
				if ((this._Kolicina != value))
				{
					this.OnKolicinaChanging(value);
					this.SendPropertyChanging();
					this._Kolicina = value;
					this.SendPropertyChanged("Kolicina");
					this.OnKolicinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaraCena", DbType="Float")]
		public System.Nullable<double> StaraCena
		{
			get
			{
				return this._StaraCena;
			}
			set
			{
				if ((this._StaraCena != value))
				{
					this.OnStaraCenaChanging(value);
					this.SendPropertyChanging();
					this._StaraCena = value;
					this.SendPropertyChanged("StaraCena");
					this.OnStaraCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NovaProdajnaCena", DbType="Float")]
		public System.Nullable<double> NovaProdajnaCena
		{
			get
			{
				return this._NovaProdajnaCena;
			}
			set
			{
				if ((this._NovaProdajnaCena != value))
				{
					this.OnNovaProdajnaCenaChanging(value);
					this.SendPropertyChanging();
					this._NovaProdajnaCena = value;
					this.SendPropertyChanged("NovaProdajnaCena");
					this.OnNovaProdajnaCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelacijaPoJM", DbType="Float")]
		public System.Nullable<double> NivelacijaPoJM
		{
			get
			{
				return this._NivelacijaPoJM;
			}
			set
			{
				if ((this._NivelacijaPoJM != value))
				{
					this.OnNivelacijaPoJMChanging(value);
					this.SendPropertyChanging();
					this._NivelacijaPoJM = value;
					this.SendPropertyChanged("NivelacijaPoJM");
					this.OnNivelacijaPoJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaraOsnovica", DbType="Float")]
		public System.Nullable<double> StaraOsnovica
		{
			get
			{
				return this._StaraOsnovica;
			}
			set
			{
				if ((this._StaraOsnovica != value))
				{
					this.OnStaraOsnovicaChanging(value);
					this.SendPropertyChanging();
					this._StaraOsnovica = value;
					this.SendPropertyChanged("StaraOsnovica");
					this.OnStaraOsnovicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StariPDV", DbType="Float")]
		public System.Nullable<double> StariPDV
		{
			get
			{
				return this._StariPDV;
			}
			set
			{
				if ((this._StariPDV != value))
				{
					this.OnStariPDVChanging(value);
					this.SendPropertyChanging();
					this._StariPDV = value;
					this.SendPropertyChanged("StariPDV");
					this.OnStariPDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NovaOsnovica", DbType="Float")]
		public System.Nullable<double> NovaOsnovica
		{
			get
			{
				return this._NovaOsnovica;
			}
			set
			{
				if ((this._NovaOsnovica != value))
				{
					this.OnNovaOsnovicaChanging(value);
					this.SendPropertyChanging();
					this._NovaOsnovica = value;
					this.SendPropertyChanged("NovaOsnovica");
					this.OnNovaOsnovicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoviPDV", DbType="Float")]
		public System.Nullable<double> NoviPDV
		{
			get
			{
				return this._NoviPDV;
			}
			set
			{
				if ((this._NoviPDV != value))
				{
					this.OnNoviPDVChanging(value);
					this.SendPropertyChanging();
					this._NoviPDV = value;
					this.SendPropertyChanged("NoviPDV");
					this.OnNoviPDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaraMarza", DbType="Float")]
		public System.Nullable<double> StaraMarza
		{
			get
			{
				return this._StaraMarza;
			}
			set
			{
				if ((this._StaraMarza != value))
				{
					this.OnStaraMarzaChanging(value);
					this.SendPropertyChanging();
					this._StaraMarza = value;
					this.SendPropertyChanged("StaraMarza");
					this.OnStaraMarzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NovaMarza", DbType="Float")]
		public System.Nullable<double> NovaMarza
		{
			get
			{
				return this._NovaMarza;
			}
			set
			{
				if ((this._NovaMarza != value))
				{
					this.OnNovaMarzaChanging(value);
					this.SendPropertyChanging();
					this._NovaMarza = value;
					this.SendPropertyChanged("NovaMarza");
					this.OnNovaMarzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumNivelacije", DbType="Date")]
		public System.Nullable<System.DateTime> DatumNivelacije
		{
			get
			{
				return this._DatumNivelacije;
			}
			set
			{
				if ((this._DatumNivelacije != value))
				{
					this.OnDatumNivelacijeChanging(value);
					this.SendPropertyChanging();
					this._DatumNivelacije = value;
					this.SendPropertyChanged("DatumNivelacije");
					this.OnDatumNivelacijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaraRUC", DbType="Float")]
		public System.Nullable<double> StaraRUC
		{
			get
			{
				return this._StaraRUC;
			}
			set
			{
				if ((this._StaraRUC != value))
				{
					this.OnStaraRUCChanging(value);
					this.SendPropertyChanging();
					this._StaraRUC = value;
					this.SendPropertyChanged("StaraRUC");
					this.OnStaraRUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NovaRUC", DbType="Float")]
		public System.Nullable<double> NovaRUC
		{
			get
			{
				return this._NovaRUC;
			}
			set
			{
				if ((this._NovaRUC != value))
				{
					this.OnNovaRUCChanging(value);
					this.SendPropertyChanging();
					this._NovaRUC = value;
					this.SendPropertyChanged("NovaRUC");
					this.OnNovaRUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrojNivelacije", DbType="Int")]
		public System.Nullable<int> BrojNivelacije
		{
			get
			{
				return this._BrojNivelacije;
			}
			set
			{
				if ((this._BrojNivelacije != value))
				{
					this.OnBrojNivelacijeChanging(value);
					this.SendPropertyChanging();
					this._BrojNivelacije = value;
					this.SendPropertyChanged("BrojNivelacije");
					this.OnBrojNivelacijeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prodavac")]
	public partial class Prodavac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProdavacID;
		
		private string _Ime;
		
		private string _KorisnickoIme;
		
		private string _Lozinka;
		
		private EntitySet<Prodavnica> _Prodavnicas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProdavacIDChanging(int value);
    partial void OnProdavacIDChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnKorisnickoImeChanging(string value);
    partial void OnKorisnickoImeChanged();
    partial void OnLozinkaChanging(string value);
    partial void OnLozinkaChanged();
    #endregion
		
		public Prodavac()
		{
			this._Prodavnicas = new EntitySet<Prodavnica>(new Action<Prodavnica>(this.attach_Prodavnicas), new Action<Prodavnica>(this.detach_Prodavnicas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdavacID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProdavacID
		{
			get
			{
				return this._ProdavacID;
			}
			set
			{
				if ((this._ProdavacID != value))
				{
					this.OnProdavacIDChanging(value);
					this.SendPropertyChanging();
					this._ProdavacID = value;
					this.SendPropertyChanged("ProdavacID");
					this.OnProdavacIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KorisnickoIme", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KorisnickoIme
		{
			get
			{
				return this._KorisnickoIme;
			}
			set
			{
				if ((this._KorisnickoIme != value))
				{
					this.OnKorisnickoImeChanging(value);
					this.SendPropertyChanging();
					this._KorisnickoIme = value;
					this.SendPropertyChanged("KorisnickoIme");
					this.OnKorisnickoImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lozinka", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Lozinka
		{
			get
			{
				return this._Lozinka;
			}
			set
			{
				if ((this._Lozinka != value))
				{
					this.OnLozinkaChanging(value);
					this.SendPropertyChanging();
					this._Lozinka = value;
					this.SendPropertyChanged("Lozinka");
					this.OnLozinkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prodavac_Prodavnica", Storage="_Prodavnicas", ThisKey="ProdavacID", OtherKey="ProdavacID")]
		public EntitySet<Prodavnica> Prodavnicas
		{
			get
			{
				return this._Prodavnicas;
			}
			set
			{
				this._Prodavnicas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prodavnicas(Prodavnica entity)
		{
			this.SendPropertyChanging();
			entity.Prodavac = this;
		}
		
		private void detach_Prodavnicas(Prodavnica entity)
		{
			this.SendPropertyChanging();
			entity.Prodavac = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnosUMagacin")]
	public partial class UnosUMagacin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UnosUMagacinID;
		
		private int _ProdavacID;
		
		private int _ProdavnicaID;
		
		private string _SifraArtikla;
		
		private System.Nullable<System.DateTime> _DatumPrijemaRobe;
		
		private string _BrojDokumentaDobavljaca;
		
		private System.Nullable<double> _TroskoviDoGranice;
		
		private System.Nullable<double> _TroskoviOdGranice;
		
		private System.Nullable<int> _DobavljacID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnosUMagacinIDChanging(int value);
    partial void OnUnosUMagacinIDChanged();
    partial void OnProdavacIDChanging(int value);
    partial void OnProdavacIDChanged();
    partial void OnProdavnicaIDChanging(int value);
    partial void OnProdavnicaIDChanged();
    partial void OnSifraArtiklaChanging(string value);
    partial void OnSifraArtiklaChanged();
    partial void OnDatumPrijemaRobeChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumPrijemaRobeChanged();
    partial void OnBrojDokumentaDobavljacaChanging(string value);
    partial void OnBrojDokumentaDobavljacaChanged();
    partial void OnTroskoviDoGraniceChanging(System.Nullable<double> value);
    partial void OnTroskoviDoGraniceChanged();
    partial void OnTroskoviOdGraniceChanging(System.Nullable<double> value);
    partial void OnTroskoviOdGraniceChanged();
    partial void OnDobavljacIDChanging(System.Nullable<int> value);
    partial void OnDobavljacIDChanged();
    #endregion
		
		public UnosUMagacin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnosUMagacinID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UnosUMagacinID
		{
			get
			{
				return this._UnosUMagacinID;
			}
			set
			{
				if ((this._UnosUMagacinID != value))
				{
					this.OnUnosUMagacinIDChanging(value);
					this.SendPropertyChanging();
					this._UnosUMagacinID = value;
					this.SendPropertyChanged("UnosUMagacinID");
					this.OnUnosUMagacinIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdavacID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProdavacID
		{
			get
			{
				return this._ProdavacID;
			}
			set
			{
				if ((this._ProdavacID != value))
				{
					this.OnProdavacIDChanging(value);
					this.SendPropertyChanging();
					this._ProdavacID = value;
					this.SendPropertyChanged("ProdavacID");
					this.OnProdavacIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdavnicaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProdavnicaID
		{
			get
			{
				return this._ProdavnicaID;
			}
			set
			{
				if ((this._ProdavnicaID != value))
				{
					this.OnProdavnicaIDChanging(value);
					this.SendPropertyChanging();
					this._ProdavnicaID = value;
					this.SendPropertyChanged("ProdavnicaID");
					this.OnProdavnicaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraArtikla", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SifraArtikla
		{
			get
			{
				return this._SifraArtikla;
			}
			set
			{
				if ((this._SifraArtikla != value))
				{
					this.OnSifraArtiklaChanging(value);
					this.SendPropertyChanging();
					this._SifraArtikla = value;
					this.SendPropertyChanged("SifraArtikla");
					this.OnSifraArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumPrijemaRobe", DbType="Date")]
		public System.Nullable<System.DateTime> DatumPrijemaRobe
		{
			get
			{
				return this._DatumPrijemaRobe;
			}
			set
			{
				if ((this._DatumPrijemaRobe != value))
				{
					this.OnDatumPrijemaRobeChanging(value);
					this.SendPropertyChanging();
					this._DatumPrijemaRobe = value;
					this.SendPropertyChanged("DatumPrijemaRobe");
					this.OnDatumPrijemaRobeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrojDokumentaDobavljaca", DbType="NVarChar(50)")]
		public string BrojDokumentaDobavljaca
		{
			get
			{
				return this._BrojDokumentaDobavljaca;
			}
			set
			{
				if ((this._BrojDokumentaDobavljaca != value))
				{
					this.OnBrojDokumentaDobavljacaChanging(value);
					this.SendPropertyChanging();
					this._BrojDokumentaDobavljaca = value;
					this.SendPropertyChanged("BrojDokumentaDobavljaca");
					this.OnBrojDokumentaDobavljacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TroskoviDoGranice", DbType="Float")]
		public System.Nullable<double> TroskoviDoGranice
		{
			get
			{
				return this._TroskoviDoGranice;
			}
			set
			{
				if ((this._TroskoviDoGranice != value))
				{
					this.OnTroskoviDoGraniceChanging(value);
					this.SendPropertyChanging();
					this._TroskoviDoGranice = value;
					this.SendPropertyChanged("TroskoviDoGranice");
					this.OnTroskoviDoGraniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TroskoviOdGranice", DbType="Float")]
		public System.Nullable<double> TroskoviOdGranice
		{
			get
			{
				return this._TroskoviOdGranice;
			}
			set
			{
				if ((this._TroskoviOdGranice != value))
				{
					this.OnTroskoviOdGraniceChanging(value);
					this.SendPropertyChanging();
					this._TroskoviOdGranice = value;
					this.SendPropertyChanged("TroskoviOdGranice");
					this.OnTroskoviOdGraniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DobavljacID", DbType="Int")]
		public System.Nullable<int> DobavljacID
		{
			get
			{
				return this._DobavljacID;
			}
			set
			{
				if ((this._DobavljacID != value))
				{
					this.OnDobavljacIDChanging(value);
					this.SendPropertyChanging();
					this._DobavljacID = value;
					this.SendPropertyChanged("DobavljacID");
					this.OnDobavljacIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
